// 🟦 SOTWE 2026 - Main Script (Compat Version)
let currentUser=null,currentUserData=null,allUsers={},allPosts=[],selectedMediaFile=null,currentChatUserId=null,viewingProfileUserId=null,currentPostForComments=null,mediaRecorder=null,audioChunks=[],bookmarks={},isAdmin=false;

async function loadUserData(){const snap=await db.ref('users/'+currentUser.uid).once('value');if(snap.exists())currentUserData={uid:currentUser.uid,...snap.val()};if(currentUserData?.bookmarks)bookmarks=currentUserData.bookmarks}
db.ref('users').on('value',s=>{allUsers=s.val()||{}});
db.ref('posts').on('value',s=>{const data=s.val();if(!data){allPosts=[];renderFeed();return}allPosts=[];Object.keys(data).forEach(k=>allPosts.push({id:k,...data[k]}));allPosts.sort((a,b)=>(b.timestamp||0)-(a.timestamp||0));renderFeed()});

async function uploadMedia(file){const fd=new FormData();fd.append('file',file);fd.append('upload_preset',UPLOAD_PRESET);let rt='image';if(file.type.startsWith('video/'))rt='video';else if(file.type.startsWith('audio/'))rt='raw';const res=await fetch('https://api.cloudinary.com/v1_1/'+CLOUD_NAME+'/'+rt+'/upload',{method:'POST',body:fd});const data=await res.json();return{url:data.secure_url,type:rt==='raw'?'audio':rt}}

function escapeHtml(text){if(!text)return '';const div=document.createElement('div');div.textContent=text;return div.innerHTML}

function renderFeed(){const c=document.getElementById('feedContainer');if(!c)return;c.innerHTML='';if(!allPosts.length){c.innerHTML='<div class="loading"><div class="spinner"></div><span>لا توجد منشورات بعد</span></div>';return}
allPosts.forEach(post=>{const user=allUsers[post.sender]||{name:post.senderName||'مستخدم',avatarUrl:''};const isLiked=post.likedBy&&post.likedBy[currentUser?.uid];const isRetweeted=post.retweetedBy&&post.retweetedBy[currentUser?.uid];const isBookmarked=bookmarks[post.id];const cc=post.comments?Object.keys(post.comments).length:0;const rc=post.retweets?Object.keys(post.retweets).length:0;
let mh='';if(post.mediaUrl){if(post.mediaType==='image')mh='<div class="tweet-media" onclick="event.stopPropagation();openImageModal(\''+post.mediaUrl+'\')"><img src="'+post.mediaUrl+'" loading="lazy"></div>';else if(post.mediaType==='video')mh='<div class="tweet-media" onclick="event.stopPropagation()"><video controls src="'+post.mediaUrl+'"></video></div>';else mh='<div class="tweet-media" onclick="event.stopPropagation()"><audio controls src="'+post.mediaUrl+'"></audio></div>'}
let qh='';if(post.quotePostId&&post.quotePostData){const qu=allUsers[post.quotePostData.sender]||{name:'مستخدم',avatarUrl:''};qh='<div class="quote-embed" onclick="event.stopPropagation();openCommentsModal(\''+post.quotePostId+'\')"><div style="display:flex;gap:8px;align-items:center;margin-bottom:6px;"><div class="comment-avatar">'+(qu.avatarUrl?'<img src="'+qu.avatarUrl+'">':(qu.name?.charAt(0)||'U'))+'</div><span style="font-weight:600;font-size:13px;">'+escapeHtml(qu.name)+'</span></div><div style="font-size:13px;">'+escapeHtml(post.quotePostData.text?.substring(0,100)||'')+'</div></div>'}
const div=document.createElement('div');div.className='tweet-card';div.onclick=()=>openCommentsModal(post.id);div.innerHTML='<div class="tweet-header"><div class="tweet-avatar" onclick="event.stopPropagation();viewProfile(\''+post.sender+'\')">'+(user.avatarUrl?'<img src="'+user.avatarUrl+'">':(user.name?.charAt(0)||'👤'))+'</div><div style="flex:1"><div><span class="tweet-name" onclick="event.stopPropagation();viewProfile(\''+post.sender+'\')">'+escapeHtml(user.name)+'</span><span class="tweet-username mx-1">@'+user.name?.toLowerCase().replace(/\s/g,'')+'</span><span class="tweet-time">· '+new Date(post.timestamp).toLocaleString()+'</span></div><div class="tweet-content">'+escapeHtml(post.text||'')+'</div>'+mh+qh+'</div></div><div class="tweet-actions" onclick="event.stopPropagation()"><button class="tweet-action" onclick="openCommentsModal(\''+post.id+'\')"><i class="far fa-comment"></i> <span>'+cc+'</span></button><button class="tweet-action '+(isRetweeted?'active':'')+'" onclick="toggleRetweet(\''+post.id+'\',this)"><i class="fas fa-retweet"></i> <span>'+rc+'</span></button><button class="tweet-action '+(isLiked?'active':'')+'" onclick="toggleLike(\''+post.id+'\',this)"><i class="fas fa-heart"></i> <span>'+(post.likes||0)+'</span></button><button class="tweet-action '+(isBookmarked?'active':'')+'" onclick="toggleBookmark(\''+post.id+'\',this)"><i class="fas fa-bookmark"></i></button><button class="tweet-action" onclick="openQuoteModal(\''+post.id+'\')"><i class="fas fa-quote-right"></i></button></div>';c.appendChild(div)})}

window.openCompose=function(){document.getElementById('composePanel').classList.add('open');document.getElementById('backBtn').style.display='flex';resetCompose()}
window.closeCompose=function(){document.getElementById('composePanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}
function resetCompose(){document.getElementById('postText').value='';document.getElementById('mediaPreview').innerHTML='';document.getElementById('mediaPreview').style.display='none';selectedMediaFile=null;document.getElementById('postImage').value='';document.getElementById('postVideo').value='';document.getElementById('postStatus').innerHTML=''}
window.previewMedia=function(input,type){const file=input.files[0];if(!file)return;selectedMediaFile=file;const reader=new FileReader();reader.onload=function(e){const mp=document.getElementById('mediaPreview');if(type==='image')mp.innerHTML='<img src="'+e.target.result+'">';else mp.innerHTML='<video controls><source src="'+e.target.result+'"></video>';mp.style.display='block'};reader.readAsDataURL(file)}
window.startAudioRecording=async function(){const btn=document.getElementById('audioRecordBtn');if(mediaRecorder&&mediaRecorder.state==='recording'){mediaRecorder.stop();btn.innerHTML='<i class="fas fa-microphone"></i>';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);audioChunks=[];mediaRecorder.ondataavailable=e=>audioChunks.push(e.data);mediaRecorder.onstop=async()=>{const blob=new Blob(audioChunks,{type:'audio/mp3'});selectedMediaFile=new File([blob],'recording.mp3',{type:'audio/mp3'});const url=URL.createObjectURL(blob);document.getElementById('mediaPreview').innerHTML='<audio controls src="'+url+'"></audio>';document.getElementById('mediaPreview').style.display='block';stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();btn.innerHTML='<i class="fas fa-stop-circle" style="color:#f91880"></i>'}catch(err){showToast('لا يمكن الوصول إلى الميكروفون')}}
window.createPost=async function(){const text=document.getElementById('postText')?.value||'';if(!text.trim()&&!selectedMediaFile){showToast('اكتب شيئاً أو اختر وسائط');return}document.getElementById('postStatus').innerHTML='📤 جاري النشر...';let mediaUrl='',mediaType='none';if(selectedMediaFile){try{const result=await uploadMedia(selectedMediaFile);mediaUrl=result.url;mediaType=result.type}catch(e){document.getElementById('postStatus').innerHTML='❌ فشل رفع الوسائط';return}}try{await db.ref('posts').push({text,mediaUrl,mediaType,sender:currentUser.uid,senderName:currentUserData?.name,likes:0,likedBy:{},retweets:{},retweetedBy:{},comments:{},timestamp:Date.now()});document.getElementById('postStatus').innerHTML='✅ تم النشر!';setTimeout(()=>closeCompose(),1500)}catch(e){document.getElementById('postStatus').innerHTML='❌ فشل النشر'}}

window.toggleLike=async function(postId,btn){if(!currentUser)return;const ref=db.ref('posts/'+postId);const snap=await ref.once('value');const post=snap.val();if(!post)return;let likes=post.likes||0;let likedBy=post.likedBy||{};if(likedBy[currentUser.uid]){likes--;delete likedBy[currentUser.uid];showToast('تم إلغاء الإعجاب')}else{likes++;likedBy[currentUser.uid]=true;addNotification(post.sender,'like',postId);showToast('❤️ أعجبتك');if(btn){const icon=btn.querySelector('i');if(icon)icon.classList.add('heart-animation');setTimeout(()=>icon?.classList.remove('heart-animation'),300)}}await ref.update({likes,likedBy});if(btn){btn.classList.toggle('active');const span=btn.querySelector('span');if(span)span.innerText=likes}}
window.toggleRetweet=async function(postId,btn){if(!currentUser)return;const ref=db.ref('posts/'+postId);const snap=await ref.once('value');const post=snap.val();if(!post)return;let retweets=post.retweets||{};let retweetedBy=post.retweetedBy||{};let rc=Object.keys(retweets).length;if(retweetedBy[currentUser.uid]){const k=Object.keys(retweets).find(k=>retweets[k].userId===currentUser.uid);if(k)delete retweets[k];delete retweetedBy[currentUser.uid];rc--;showToast('تم إلغاء إعادة التغريد')}else{retweets[Date.now().toString()]={userId:currentUser.uid,timestamp:Date.now()};retweetedBy[currentUser.uid]=true;rc++;addNotification(post.sender,'retweet',postId);showToast('🔁 تم إعادة التغريد')}await ref.update({retweets,retweetedBy});if(btn){btn.classList.toggle('active');const span=btn.querySelector('span');if(span)span.innerText=rc}}
window.toggleBookmark=async function(postId,btn){if(!currentUser)return;const ref=db.ref('users/'+currentUser.uid+'/bookmarks/'+postId);const snap=await ref.once('value');if(snap.exists()){await ref.set(null);delete bookmarks[postId];showToast('تمت إزالة من الإشارات المرجعية')}else{await ref.set(true);bookmarks[postId]=true;showToast('📌 تمت إضافة إلى الإشارات المرجعية')}if(btn)btn.classList.toggle('active')}
window.openQuoteModal=function(postId){const text=prompt('أضف تعليقك على هذا المنشور:');if(text)createQuotePost(postId,text)}
async function createQuotePost(opid,text){const op=allPosts.find(p=>p.id===opid);if(!op)return;await db.ref('posts').push({text,mediaUrl:'',mediaType:'none',sender:currentUser.uid,senderName:currentUserData?.name,quotePostId:opid,quotePostData:{text:op.text,sender:op.sender,senderName:op.senderName,mediaUrl:op.mediaUrl,mediaType:op.mediaType},likes:0,likedBy:{},retweets:{},retweetedBy:{},comments:{},timestamp:Date.now()});addNotification(op.sender,'quote',opid);showToast('✅ تم نشر الاقتباس')}

window.openCommentsModal=async function(postId){currentPostForComments=postId;const post=allPosts.find(p=>p.id===postId);if(!post)return;const c=document.getElementById('commentsList');const comments=post.comments||{};c.innerHTML='';const sorted=Object.entries(comments).sort((a,b)=>b[1].timestamp-a[1].timestamp);for(const[ck,comment]of sorted){const user=allUsers[comment.userId]||{name:comment.username||'مستخدم',avatarUrl:''};const replies=comment.replies||{};const cd=document.createElement('div');cd.className='comment-item';cd.innerHTML='<div class="comment-header"><div class="comment-avatar" onclick="viewProfile(\''+comment.userId+'\')">'+(user.avatarUrl?'<img src="'+user.avatarUrl+'">':(user.name?.charAt(0)||'U'))+'</div><div style="flex:1"><div><span class="comment-user" onclick="viewProfile(\''+comment.userId+'\')">'+escapeHtml(user.name)+'</span><span class="comment-time mx-2">· '+new Date(comment.timestamp).toLocaleString()+'</span></div><div class="comment-text">'+escapeHtml(comment.text)+'</div></div></div><div class="reply-list" id="replies-'+ck+'"></div><div><button style="color:#1d9bf0;font-size:14px;margin-top:8px;" onclick="showReplyInput(\''+ck+'\')"><i class="fas fa-reply"></i> رد</button></div><div id="reply-input-'+ck+'" style="margin-top:8px;"></div>';const rc=cd.querySelector('#replies-'+ck);if(rc&&replies){const sr=Object.entries(replies).sort((a,b)=>a[1].timestamp-b[1].timestamp);for(const[rk,reply]of sr){const ru=allUsers[reply.userId]||{name:reply.username||'مستخدم',avatarUrl:''};rc.innerHTML+='<div class="reply-item"><div class="reply-header"><div class="reply-avatar" onclick="viewProfile(\''+reply.userId+'\')">'+(ru.avatarUrl?'<img src="'+ru.avatarUrl+'">':(ru.name?.charAt(0)||'U'))+'</div><div class="reply-user" onclick="viewProfile(\''+reply.userId+'\')">'+escapeHtml(ru.name)+'</div><div class="comment-time">'+new Date(reply.timestamp).toLocaleTimeString()+'</div></div><div class="reply-text">'+escapeHtml(reply.text)+'</div></div>'}}c.appendChild(cd)}if(c.innerHTML==='')c.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">لا توجد تعليقات بعد</div>';document.getElementById('commentsPanel').classList.add('open');document.getElementById('backBtn').style.display='flex'}
window.closeComments=function(){document.getElementById('commentsPanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}
window.showReplyInput=function(commentId){const d=document.getElementById('reply-input-'+commentId);if(!d)return;if(d.innerHTML){d.innerHTML='';return}d.innerHTML='<div style="display:flex;gap:8px;"><input type="text" id="reply-text-'+commentId+'" style="flex:1;background:#1a1a2a;border:1px solid #2f3336;border-radius:40px;padding:8px 12px;color:#fff;font-size:13px;outline:none;" placeholder="اكتب رداً..." onkeypress="if(event.key===\'Enter\')addReply(\''+commentId+'\')"><button onclick="addReply(\''+commentId+'\')" style="background:#1d9bf0;color:#fff;border:none;padding:8px 16px;border-radius:40px;font-size:13px;cursor:pointer;">نشر</button></div>'}
window.addReply=async function(commentId){const input=document.getElementById('reply-text-'+commentId);const text=input?.value;if(!text?.trim())return;await db.ref('posts/'+currentPostForComments+'/comments/'+commentId+'/replies').push({userId:currentUser.uid,username:currentUserData?.name,text,timestamp:Date.now()});if(input)input.value='';openCommentsModal(currentPostForComments)}
window.addComment=async function(){const input=document.getElementById('commentInput');const text=input?.value;if(!text?.trim()||!currentPostForComments)return;await db.ref('posts/'+currentPostForComments+'/comments').push({userId:currentUser.uid,username:currentUserData?.name,text,replies:{},timestamp:Date.now()});if(input)input.value='';openCommentsModal(currentPostForComments);const post=allPosts.find(p=>p.id===currentPostForComments);if(post)addNotification(post.sender,'comment',currentPostForComments)}

async function addNotification(targetUserId,type,postId=null){if(targetUserId===currentUser.uid)return;const messages={like:'❤️ أعجب بمنشورك',comment:'💬 علق على منشورك',retweet:'🔁 أعاد تغريد منشورك',quote:'📝 اقتبس منشورك',follow:'👥 بدأ بمتابعتك'};await db.ref('notifications/'+targetUserId).push({type,fromUserId:currentUser.uid,fromUsername:currentUserData?.name,message:messages[type],postId:postId,timestamp:Date.now(),read:false});updateNotificationBadge()}
function updateNotificationBadge(){if(!currentUser?.uid)return;db.ref('notifications/'+currentUser.uid).on('value',snap=>{const notifs=snap.val()||{};const unread=Object.values(notifs).filter(n=>!n.read).length;const badge=document.getElementById('notifBadge');if(badge){if(unread>0){badge.style.display='flex';badge.innerText=unread>9?'9+':unread}else badge.style.display='none'}})}
window.openNotifications=async function(){const panel=document.getElementById('notificationsPanel');const snap=await db.ref('notifications/'+currentUser.uid).once('value');const notifs=snap.val()||{};const c=document.getElementById('notificationsList');c.innerHTML='';const sorted=Object.entries(notifs).sort((a,b)=>b[1].timestamp-a[1].timestamp);for(const[key,n]of sorted){const icons={like:'❤️',comment:'💬',retweet:'🔁',quote:'📝',follow:'👥'};const bg=n.read?'':'background:rgba(29,155,240,0.1);border-right:4px solid #1d9bf0;';c.innerHTML+='<div class="notification-item" style="'+bg+'" onclick="handleNotificationClick(\''+n.type+'\',\''+n.fromUserId+'\',\''+(n.postId||'')+'\')"><div style="font-size:24px;">'+(icons[n.type]||'🔔')+'</div><div style="flex:1"><div style="font-weight:700;">'+escapeHtml(n.fromUsername)+'</div><div style="font-size:14px;color:#71767b;">'+n.message+'</div><div style="font-size:12px;color:#71767b;margin-top:4px;">'+new Date(n.timestamp).toLocaleString()+'</div></div></div>';if(!n.read)await db.ref('notifications/'+currentUser.uid+'/'+key).update({read:true})}if(c.innerHTML==='')c.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">لا توجد إشعارات</div>';panel.classList.add('open');document.getElementById('backBtn').style.display='flex'}
window.handleNotificationClick=function(type,userId,postId){closeNotifications();if(type==='follow')viewProfile(userId);else if(postId)openCommentsModal(postId)}
window.closeNotifications=function(){document.getElementById('notificationsPanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}

function showToast(msg){let t=document.getElementById('customToast');if(!t){t=document.createElement('div');t.id='customToast';document.body.appendChild(t)}t.innerText=msg;t.style.opacity='1';setTimeout(()=>{t.style.opacity='0'},3000)}

window.openMyProfile=function(){viewProfile(currentUser.uid)}
window.viewProfile=async function(userId){if(!userId)return;viewingProfileUserId=userId;await loadProfileData(userId);document.getElementById('profilePanel').classList.add('open');document.getElementById('backBtn').style.display='flex'}
window.closeProfile=function(){document.getElementById('profilePanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}
async function loadProfileData(userId){const snap=await db.ref('users/'+userId).once('value');const user=snap.val();if(!user)return;const cover=document.getElementById('profileCover');if(user.coverUrl)cover.style.background='url('+user.coverUrl+') center/cover';else cover.style.background='linear-gradient(135deg,#1d9bf0,#f91880)';document.getElementById('profileAvatar').innerHTML=user.avatarUrl?'<img src="'+user.avatarUrl+'">':(user.name?.charAt(0)||'👤');document.getElementById('profileName').innerText=user.name;document.getElementById('profileBio').innerText=user.bio||'✏️ أضف سيرة ذاتية';const ups=allPosts.filter(p=>p.sender===userId);document.getElementById('profilePostsCount').innerText=ups.length;document.getElementById('profileFollowersCount').innerText=Object.keys(user.followers||{}).length;document.getElementById('profileFollowingCount').innerText=Object.keys(user.following||{}).length;const grid=document.getElementById('profilePostsGrid');grid.innerHTML=ups.map(p=>'<div class="profile-post" onclick="openCommentsModal(\''+p.id+'\')">'+(p.mediaUrl?(p.mediaType==='image'?'<img src="'+p.mediaUrl+'" loading="lazy">':p.mediaType==='video'?'<video src="'+p.mediaUrl+'"></video>':'<i class="fas fa-music" style="font-size:24px;"></i>'):'<i class="fas fa-file-alt" style="font-size:24px;"></i>')+'</div>').join('');if(!ups.length)grid.innerHTML='<div style="grid-column:1/-1;text-align:center;color:#71767b;padding:40px;">لا توجد منشورات</div>';const bd=document.getElementById('profileButtons');bd.innerHTML='';if(userId===currentUser.uid){bd.innerHTML='<button class="profile-btn btn-primary" onclick="openEditProfileModal()">✏️ تعديل الملف</button><button class="profile-btn btn-secondary" onclick="logout()">🚪 تسجيل خروج</button>'+(isAdmin?'<button class="profile-btn btn-secondary" onclick="openAdmin()">🔧 لوحة التحكم</button>':'')}else{const isF=currentUserData?.following&&currentUserData.following[userId];bd.innerHTML='<button class="profile-btn btn-primary" onclick="toggleFollow(\''+userId+'\',this)">'+(isF?'✅ متابع':'➕ متابعة')+'</button><button class="profile-btn btn-secondary" onclick="openPrivateChat(\''+userId+'\')"><i class="fas fa-envelope"></i> مراسلة</button>'}}

window.openEditProfileModal=function(){document.getElementById('editName').value=currentUserData?.name||'';document.getElementById('editBio').value=currentUserData?.bio||'';document.getElementById('editProfileModal').classList.add('open')}
window.closeEditProfileModal=function(){document.getElementById('editProfileModal').classList.remove('open')}
window.saveProfileEdit=async function(){const name=document.getElementById('editName').value;const bio=document.getElementById('editBio').value;if(!name.trim()){showToast('الاسم مطلوب');return}await db.ref('users/'+currentUser.uid).update({name:name.trim(),bio});showToast('✅ تم تحديث الملف الشخصي');closeEditProfileModal();setTimeout(()=>location.reload(),1000)}

window.changeAvatar=function(){document.getElementById('avatarInput')?.click()}
window.changeCover=function(){document.getElementById('coverInput')?.click()}
(function(){if(!document.getElementById('avatarInput')){const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.id='avatarInput';inp.style.display='none';document.body.appendChild(inp);inp.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;showToast('📤 جاري رفع الصورة...');const result=await uploadMedia(file);await db.ref('users/'+currentUser.uid).update({avatarUrl:result.url});showToast('✅ تم تحديث الصورة الشخصية');location.reload()})}if(!document.getElementById('coverInput')){const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.id='coverInput';inp.style.display='none';document.body.appendChild(inp);inp.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;showToast('📤 جاري رفع الصورة...');const result=await uploadMedia(file);await db.ref('users/'+currentUser.uid).update({coverUrl:result.url});showToast('✅ تم تحديث صورة الغلاف');location.reload()})}})()

window.toggleFollow=async function(userId,btn){if(!currentUser||currentUser.uid===userId)return;const ref=db.ref('users/'+currentUser.uid+'/following/'+userId);const tref=db.ref('users/'+userId+'/followers/'+currentUser.uid);const snap=await ref.once('value');if(snap.exists()){await ref.set(null);await tref.set(null);if(btn)btn.innerText='➕ متابعة';showToast('👋 توقفت عن متابعة '+(allUsers[userId]?.name||''))}else{await ref.set(true);await tref.set(true);if(btn)btn.innerText='✅ متابع';addNotification(userId,'follow');showToast('👥 بدأت بمتابعة '+(allUsers[userId]?.name||''))}if(viewingProfileUserId===userId)await loadProfileData(userId)}
window.openFollowersList=async function(type){document.getElementById('followersTitle').innerText=type==='followers'?'المتابعون':'المتابَعون';const c=document.getElementById('followersList');const user=viewingProfileUserId?allUsers[viewingProfileUserId]:currentUserData;const list=type==='followers'?user?.followers:user?.following;c.innerHTML='';if(list){for(const[uid]of Object.entries(list)){const u=allUsers[uid];if(u)c.innerHTML+='<div class="follower-item" onclick="viewProfile(\''+uid+'\')"><div class="avatar-xs">'+(u.avatarUrl?'<img src="'+u.avatarUrl+'">':(u.name?.charAt(0)||'U'))+'</div><div><div style="font-weight:700;">'+escapeHtml(u.name)+'</div><div style="font-size:13px;color:#71767b;">@'+u.name?.toLowerCase().replace(/\s/g,'')+'</div></div></div>'}}if(c.innerHTML==='')c.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">لا يوجد مستخدمين</div>';document.getElementById('followersPanel').classList.add('open');document.getElementById('backBtn').style.display='flex'}
window.closeFollowers=function(){document.getElementById('followersPanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}

function getChatId(u1,u2){return u1<u2?u1+'_'+u2:u2+'_'+u1}
window.openConversations=async function(){const panel=document.getElementById('conversationsPanel');const c=document.getElementById('conversationsList');const snap=await db.ref('private_chats/'+currentUser.uid).once('value');const convs=snap.val()||{};c.innerHTML='';for(const[oid,cd]of Object.entries(convs)){const u=allUsers[oid];if(u)c.innerHTML+='<div class="conversation-item" onclick="openPrivateChat(\''+oid+'\')"><div class="avatar-sm">'+(u.avatarUrl?'<img src="'+u.avatarUrl+'">':(u.name?.charAt(0)||'U'))+'</div><div><div style="font-weight:700;">'+escapeHtml(u.name)+'</div><div style="font-size:13px;color:#71767b;">'+(cd.lastMessage?.substring(0,40)||'رسالة')+'</div></div></div>'}if(c.innerHTML==='')c.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">لا توجد محادثات بعد</div>';panel.classList.add('open');document.getElementById('backBtn').style.display='flex'}
window.closeConversations=function(){document.getElementById('conversationsPanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}
window.openPrivateChat=async function(oid){currentChatUserId=oid;const u=allUsers[oid];document.getElementById('chatUserName').innerText=u?.name||'مستخدم';document.getElementById('chatAvatar').innerHTML=u?.avatarUrl?'<img src="'+u.avatarUrl+'">':(u?.name?.charAt(0)||'U');await loadPrivateMessages(oid);document.getElementById('chatPanel').classList.add('open');document.getElementById('backBtn').style.display='flex';closeConversations()}
window.closeChat=function(){document.getElementById('chatPanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none';currentChatUserId=null}
async function loadPrivateMessages(oid){const c=document.getElementById('chatMessages');c.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">جاري التحميل...</div>';const chatId=getChatId(currentUser.uid,oid);const snap=await db.ref('private_messages/'+chatId).once('value');const msgs=snap.val()||{};c.innerHTML='';const sorted=Object.entries(msgs).sort((a,b)=>a[1].timestamp-b[1].timestamp);for(const[id,msg]of sorted){const sent=msg.senderId===currentUser.uid;const time=new Date(msg.timestamp).toLocaleTimeString();let content='';if(msg.type==='text')content='<div class="message-bubble '+(sent?'sent':'received')+'">'+escapeHtml(msg.text)+'</div>';else if(msg.type==='image')content='<img src="'+msg.imageUrl+'" class="message-image" onclick="openImageModal(\''+msg.imageUrl+'\')">';else if(msg.type==='audio')content='<div class="message-audio"><audio controls src="'+msg.audioUrl+'"></audio></div>';c.innerHTML+='<div class="chat-message '+(sent?'sent':'received')+'"><div>'+content+'<div style="font-size:10px;opacity:0.5;margin-top:4px;">'+time+'</div></div></div>'}if(c.innerHTML==='')c.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">لا توجد رسائل بعد</div>';c.scrollTop=c.scrollHeight}
window.sendChatMessage=async function(){const input=document.getElementById('chatMessageInput');const text=input?.value.trim();if(!text||!currentChatUserId)return;const chatId=getChatId(currentUser.uid,currentChatUserId);await db.ref('private_messages/'+chatId).push({senderId:currentUser.uid,senderName:currentUserData?.name,text,type:'text',timestamp:Date.now()});await db.ref('private_chats/'+currentUser.uid+'/'+currentChatUserId).set({lastMessage:text,lastTimestamp:Date.now(),withUser:currentChatUserId});await db.ref('private_chats/'+currentChatUserId+'/'+currentUser.uid).set({lastMessage:text,lastTimestamp:Date.now(),withUser:currentUser.uid});input.value='';await loadPrivateMessages(currentChatUserId)}
window.sendChatImage=async function(input){const file=input.files[0];if(!file||!currentChatUserId)return;const result=await uploadMedia(file);const chatId=getChatId(currentUser.uid,currentChatUserId);await db.ref('private_messages/'+chatId).push({senderId:currentUser.uid,senderName:currentUserData?.name,imageUrl:result.url,type:'image',timestamp:Date.now()});await db.ref('private_chats/'+currentUser.uid+'/'+currentChatUserId).set({lastMessage:'📷 صورة',lastTimestamp:Date.now(),withUser:currentChatUserId});await db.ref('private_chats/'+currentChatUserId+'/'+currentUser.uid).set({lastMessage:'📷 صورة',lastTimestamp:Date.now(),withUser:currentUser.uid});input.value='';await loadPrivateMessages(currentChatUserId)}
window.startRecordingChat=async function(){const btn=document.getElementById('chatRecordBtn');if(mediaRecorder&&mediaRecorder.state==='recording'){mediaRecorder.stop();btn.innerHTML='<i class="fas fa-microphone"></i>';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);audioChunks=[];mediaRecorder.ondataavailable=e=>audioChunks.push(e.data);mediaRecorder.onstop=async()=>{const blob=new Blob(audioChunks,{type:'audio/mp3'});const file=new File([blob],'recording.mp3',{type:'audio/mp3'});const result=await uploadMedia(file);if(currentChatUserId){const chatId=getChatId(currentUser.uid,currentChatUserId);await db.ref('private_messages/'+chatId).push({senderId:currentUser.uid,senderName:currentUserData?.name,audioUrl:result.url,type:'audio',timestamp:Date.now()});await db.ref('private_chats/'+currentUser.uid+'/'+currentChatUserId).set({lastMessage:'🎤 رسالة صوتية',lastTimestamp:Date.now(),withUser:currentChatUserId});await db.ref('private_chats/'+currentChatUserId+'/'+currentUser.uid).set({lastMessage:'🎤 رسالة صوتية',lastTimestamp:Date.now(),withUser:currentUser.uid});await loadPrivateMessages(currentChatUserId)}stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();btn.innerHTML='<i class="fas fa-stop-circle" style="color:#f91880"></i>'}catch(err){showToast('لا يمكن الوصول إلى الميكروفون')}}

window.openSearch=function(){document.getElementById('searchPanel').classList.add('open');document.getElementById('backBtn').style.display='flex'}
window.closeSearch=function(){document.getElementById('searchPanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}
window.searchAll=function(){const q=document.getElementById('searchInput').value.toLowerCase();const r=document.getElementById('searchResults');if(!q){r.innerHTML='';return}const users=Object.values(allUsers).filter(u=>u.name?.toLowerCase().includes(q));r.innerHTML=users.map(u=>'<div class="search-result" onclick="viewProfile(\''+u.uid+'\')"><div class="avatar-xs">'+(u.avatarUrl?'<img src="'+u.avatarUrl+'">':(u.name?.charAt(0)||'U'))+'</div><div><div style="font-weight:700;">'+escapeHtml(u.name)+'</div><div style="font-size:13px;color:#71767b;">@'+u.name?.toLowerCase().replace(/\s/g,'')+'</div></div></div>').join('');if(!users.length)r.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">لا توجد نتائج</div>'}

window.openAdmin=async function(){if(!isAdmin)return;const tu=Object.keys(allUsers).length;const tp=allPosts.length;const tl=allPosts.reduce((s,p)=>s+(p.likes||0),0);const tc=allPosts.reduce((s,p)=>s+(p.comments?Object.keys(p.comments).length:0),0);document.getElementById('adminStats').innerHTML='<div class="admin-stat"><div class="admin-stat-icon"><i class="fas fa-users"></i></div><div class="admin-stat-number">'+tu+'</div><div class="admin-stat-label">مستخدمين</div></div><div class="admin-stat"><div class="admin-stat-icon"><i class="fas fa-file-alt"></i></div><div class="admin-stat-number">'+tp+'</div><div class="admin-stat-label">منشورات</div></div><div class="admin-stat"><div class="admin-stat-icon" style="color:#f91880;"><i class="fas fa-heart"></i></div><div class="admin-stat-number">'+tl+'</div><div class="admin-stat-label">إعجابات</div></div><div class="admin-stat"><div class="admin-stat-icon" style="color:#1d9bf0;"><i class="fas fa-comment"></i></div><div class="admin-stat-number">'+tc+'</div><div class="admin-stat-label">تعليقات</div></div>';const ul=document.getElementById('adminUsersList');ul.innerHTML='';Object.entries(allUsers).forEach(([uid,u])=>{if(uid!==currentUser.uid)ul.innerHTML+='<div class="admin-item"><div><div class="admin-item-name">'+escapeHtml(u.name)+'</div><div class="admin-item-email">'+u.email+'</div></div><button class="admin-delete-btn" onclick="adminDeleteUser(\''+uid+'\')"><i class="fas fa-trash"></i> حذف</button></div>'});if(ul.innerHTML==='')ul.innerHTML='<div style="text-align:center;color:#71767b;padding:40px;">لا يوجد مستخدمين آخرين</div>';const pl=document.getElementById('adminPostsList');pl.innerHTML='';allPosts.slice(0,30).forEach(p=>{pl.innerHTML+='<div class="admin-item"><div><div class="admin-item-name">'+escapeHtml(p.senderName||'مستخدم')+'</div><div class="admin-item-text">'+(p.text?.substring(0,60)||'منشور بدون نص')+'</div><div class="admin-item-email">'+new Date(p.timestamp).toLocaleString()+'</div></div><button class="admin-delete-btn" onclick="adminDeletePost(\''+p.id+'\')"><i class="fas fa-trash"></i> حذف</button></div>'});document.getElementById('adminPanel').classList.add('open');document.getElementById('backBtn').style.display='flex'}
window.closeAdmin=function(){document.getElementById('adminPanel').classList.remove('open');if(!document.querySelector('.panel.open'))document.getElementById('backBtn').style.display='none'}
window.adminDeleteUser=async function(uid){if(!isAdmin||!confirm('⚠️ حذف هذا المستخدم وجميع منشوراته؟'))return;const posts=allPosts.filter(p=>p.sender===uid);for(const p of posts)await db.ref('posts/'+p.id).set(null);await db.ref('users/'+uid).set(null);showToast('✅ تم حذف المستخدم');location.reload()}
window.adminDeletePost=async function(pid){if(!isAdmin||!confirm('⚠️ حذف هذا المنشور؟'))return;await db.ref('posts/'+pid).set(null);showToast('✅ تم حذف المنشور');renderFeed()}

window.switchTab=function(tab){document.querySelectorAll('.nav-item').forEach(t=>t.classList.remove('active'));if(event&&event.target){const clicked=event.target.closest('.nav-item');if(clicked)clicked.classList.add('active')}if(tab==='home'){closeCompose();closeProfile();closeChat();closeConversations();closeNotifications();closeSearch();closeComments();closeFollowers();closeAdmin();closeEditProfileModal()}}
window.goToHome=function(){const hb=document.querySelector('.nav-item i.fa-home')?.closest('.nav-item');if(hb){document.querySelectorAll('.nav-item').forEach(t=>t.classList.remove('active'));hb.classList.add('active')}closeCompose();closeProfile();closeChat();closeConversations();closeNotifications();closeSearch();closeComments();closeFollowers();closeAdmin();closeEditProfileModal();document.getElementById('backBtn').style.display='none'}
window.goBack=function(){if(document.getElementById('commentsPanel')?.classList.contains('open'))closeComments();else if(document.getElementById('profilePanel')?.classList.contains('open'))closeProfile();else if(document.getElementById('chatPanel')?.classList.contains('open'))closeChat();else if(document.getElementById('conversationsPanel')?.classList.contains('open'))closeConversations();else if(document.getElementById('notificationsPanel')?.classList.contains('open'))closeNotifications();else if(document.getElementById('searchPanel')?.classList.contains('open'))closeSearch();else if(document.getElementById('followersPanel')?.classList.contains('open'))closeFollowers();else if(document.getElementById('adminPanel')?.classList.contains('open'))closeAdmin();else if(document.getElementById('composePanel')?.classList.contains('open'))closeCompose();else if(document.getElementById('editProfileModal')?.classList.contains('open'))closeEditProfileModal();else goToHome()}
window.logout=function(){auth.signOut();location.reload()}

auth.onAuthStateChanged(async user=>{if(user){currentUser=user;await loadUserData();isAdmin=ADMIN_EMAILS.includes(currentUser.email);document.getElementById('mainApp').style.display='block';updateNotificationBadge();if(localStorage.getItem('theme')==='light')document.body.classList.add('light-mode');showToast('👋 مرحباً '+(currentUserData?.name||'مستخدم'))}else{window.location.replace('auth.html')}})
console.log('🟦 Sotwe Platform Ready ✨')
